#!/usr/bin/env bash
# Refreshes the CodeGraph index, which cannot read claude-retrier.sh on its own:
# the wrapper is Python inside a bash heredoc, and no parser takes that whole.
#
#   ./test/codegraph-sync.sh      # after editing claude-retrier.sh
#
# So the Python is mirrored into a file CodeGraph can parse, with every line
# outside the heredoc blanked to a bare "#" rather than dropped. Line N of the
# mirror is therefore line N of claude-retrier.sh, and a line number CodeGraph
# reports can be opened in the real file as it stands.
#
# The mirror is generated and gitignored. Never edit it: edit claude-retrier.sh
# and run this again.
set -u
cd "$(dirname "$0")/.." || exit 1

SRC=claude-retrier.sh
OUT_DIR=.codegraph-src
OUT=$OUT_DIR/$SRC.py

mkdir -p "$OUT_DIR" || exit 1

awk '
  NR == 1 { print "# GENERATED by test/codegraph-sync.sh from claude-retrier.sh. DO NOT EDIT."; next }
  NR == 2 { print "# Line N here is line N of claude-retrier.sh: edit THAT file, then re-run the script."; next }
  /^CR_PYTHON_EOF$/ { inpy = 0 }
  inpy { print; next }
  { print "#" }
  /<<.CR_PYTHON_EOF./ { inpy = 1 }
' "$SRC" >"$OUT.tmp" || exit 1

# A mirror that does not parse would index as next to nothing, silently — which
# is exactly the state this script exists to get out of.
if ! "${PYTHON:-python3}" -c 'import ast, sys; ast.parse(open(sys.argv[1]).read())' "$OUT.tmp"; then
  rm -f "$OUT.tmp"
  echo "codegraph-sync: the mirror of $SRC is not valid Python; nothing was changed" >&2
  exit 1
fi

if [ "$(wc -l <"$SRC")" -ne "$(wc -l <"$OUT.tmp")" ]; then
  rm -f "$OUT.tmp"
  echo "codegraph-sync: the mirror lost or gained lines; nothing was changed" >&2
  exit 1
fi

mv "$OUT.tmp" "$OUT" || exit 1
echo "mirrored $SRC -> $OUT"

command -v codegraph >/dev/null 2>&1 || { echo "codegraph is not installed; mirror written, index untouched"; exit 0; }
if [ -d .codegraph ]; then
  codegraph sync . -q
else
  codegraph init .
fi
